version: "3"

services:
  uploader:
    build: .
    container_name: "uploader"
    extra_hosts:
      - "database:host-gateway"
    networks:
      main:
    volumes:
      - /home/penumbra/images/:/etc/images/:rw
      - /home/penumbra/audio/:/etc/audio/:rw

networks:
  main:
    external: true
