[tool.poetry]
name = "abstractumbra-cdn"
version = "0.1.0"
description = ""
authors = ["Alex Nørgaard <Umbra@AbstractUmbra.xyz>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.65.2"
toml = "^0.10.2"
uvicorn = "^0.12.2"
python-multipart = "^0.0.5"
asyncpg = "^0.21.0"
PyJWT = "^1.7.1"
pycryptodome = "^3.9.9"

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"
autopep8 = "^1.5.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
