[database]
dsn = "postgresql://cdn:ImageHost!1231@195.154.69.209:32932/cdn"
user = "cdn"
password = "ImageHost!1231"
schema = "schema.sql"

[users]
100 = {name = "Umbra", token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MTAwfQ.-sTRI5u_Ger14I4L5v1Q5G53kj1Cr5zjFVT_4LNafHGRdeAmKx0FzSp8Jr6xxr5vCPICjlHlPyqLIVu7qL6HAw"}
101 = {name = "Kaylynn", token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6MTAxfQ.NMk-ZgUpPL-Pz_Wyn04uZuPAkCvzMddmnMCMr1S0BpaDnUi8EgLs33BSVbhJQbDsH1WT8m4p7o_nT94lSPSCCA"}

[web]
100 = [
    "https://umbra-is.gay",
    "https://umbra.might-be.gay"
]
101 = [
    "https://kaylynn.might-be.gay"
]